import { Dimensions, Platform } from "react-native";

export const COLORS = {
  light: {
    backgroundColor: "#ffffff",
    textColor: "#262626",
    lightTextColor: "#737373",
    secondaryColor: "#0b66c3",
    wrapperColor: "#f9fafc",
    danger: "#ff3040",
    link: "#0b66c3",
    borderLines: "#4A4E51",
    inputColor: "#f9fafc",
    lightBorder: "#0b66c3",
    backColor: "#000000",
    borderColor: "#E1E1E1",
    tagColor: "#5AB5FA",
    tabBorderColor: "#E1E1E1",
    senderChatColor: "#0b66c3",
    receiveChatColor: "#606676",
    dropDownColor: "#070911",
    lightWhite: "#e1e1e1",
    voiceLine: "#d742bf",
    feedbackText: "#e1e1e1",
    shimmerColor1: "#e0e0e0",
    shimmerColor2: "#f5f5f5",
    loadingOverlayBackground: "rgba(0, 0, 0, 0.50)",
    languageDropDownColor: "#070911",
    selectedLanguage: "rgba(115, 115, 115, 0.20)",
    background: "#FFFFFF",
    surface: "#F8F8F8",
    primary: "#1A1A1A",
    secondary: "#666666",
    border: "#EEEEEE",
    text: "#1A1A1A",
    textSecondary: "#666666",
    placeholder: "#999999",
    disabled: "#CCCCCC",
    overlay: "rgba(0, 0, 0, 0.7)",
  },
  dark: {
    backgroundColor: "#000000",
    textColor: "#f5f5f5",
    lightTextColor: "#a8a8a8",
    secondaryColor: "rgb(10, 132, 255)",
    wrapperColor: "#f9fafc",
    danger: "#ff3040",
    link: "#f19c12",
    borderLines: "#4A4E51",
    inputColor: "#181D2C",
    lightBorder: "#3BF6F1",
    backColor: "#FFFFFF",
    borderColor: "#A0A0A0",
    tagColor: "#5AB5FA",
    tabBorderColor: "#4A4E51",
    senderChatColor: "#3F43F2",
    receiveChatColor: "#0F111B",
    dropDownColor: "#070911",
    lightWhite: "#e1e1e1",
    voiceLine: "#d742bf",
    feedbackText: "#a8a8a8",
    shimmerColor1: "#1E2433",
    shimmerColor2: "#292F40",
    loadingOverlayBackground: "rgba(24, 29, 44, 0.8)",
    languageDropDownColor: "#f9fafc",
    selectedLanguage: "rgba(115, 115, 115, 0.20)",
    background: "#121212",
    surface: "#1E1E1E",
    primary: "#FFFFFF",
    secondary: "#AAAAAA",
    border: "#2C2C2C",
    text: "#FFFFFF",
    textSecondary: "#AAAAAA",
    placeholder: "#666666",
    disabled: "#444444",
    overlay: "rgba(255, 255, 255, 0.1)",
  },
};

export const FONTS = Platform.select({
  ios: {
    sans: "system-ui",
    serif: "ui-serif",
    rounded: "ui-rounded",
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

export const SCREEN_WIDTH = Dimensions.get("window").width;
export const SCREEN_HEIGHT = Dimensions.get("window").height;
